---
-name: Create Ec2 instances
 hosts: localhost
 connection: local

 tasks:
 -name: Create Ec2 Instances
  amazon.aws.ec2.instance:
    name: "{{ item.name }}"
    key_name: "spurthi_key"
    instance_group: t2.micro
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ec2_access_key}}" # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}" # From vault as defined
    network:
      assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      environment: "{{ item.name }}"
 loop:
   - { image: "ami-bbdsafbashfbh6723", name: "manage-node-1" }
   - { image: "ami-bbdsafbashfbh6723", name: "manage-node-2" }
   - { image: "ami-bbdsafbashfbh6334", name: "manage-node-3" }
