pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/SpurthiHiremath/Ansible.git'
            }
        }
        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'Ansible/Jenkins_Ansible_Integration/deploy.yml',
                    inventory: 'Ansible/Jenkins_Ansible_Integration/inventory.ini'
                )
            }
        }
    }
}
