
---
- name: example play
  hosts: all
  remote_user: root

  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: longrunner
    command: /bin/sleep 15
   
  - name: Copy File
    cp: 
      src: /NestedPlaybooks/tasks/test.txt 
      dest: /NestedPlaybooks/tasks/target/
    notify:
    - restart apache

  - name: install httpd
    yum: 
       pkg: httpd
       state: latest

  - name: httpd start
    service: 
       name: httpd 
       state: running

  handlers:
    - name: restart apache
      service: 
        name: httpd 
        state: restarted
