---
# tasks file for apache_role

- name: Install httpd package
  yum:
    name: httpd
    state: present
  become: yes

- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
